default: &default
  adapter: mysql2
  encoding: utf8
  database: qotd
  username: root
  host: 127.0.0.1
  port: 3306

development:
  <<: *default

test:
  <<: *default

production:
  adapter: mysql2
  encoding: utf8
  database: "<%= ENV["QOTD_MYSQL_PRODUCTION_DATABASE"] %>"
  username: "<%= ENV["QOTD_MYSQL_PRODUCTION_USERNAME"] %>"
  password: "<%= ENV["QOTD_MYSQL_PRODUCTION_PASSWORD"] %>"
  host: "<%= ENV["QOTD_MYSQL_PRODUCTION_HOST"] %>"
  port: <%= ENV["QOTD_MYSQL_PRODUCTION_PORT"] %>
